/**
 * enemyDefinitions.ts — Act 1 normal enemy roster.
 *
 * To add a new enemy: add an entry here (or in a new file merged in act1.ts),
 * pick a `behavior`, point `sprite` at an AssetManager key, and give it a
 * `fallbackColor` for the procedural shape. Place it in a room via a SpawnDef
 * with kind "enemy" and ref = the id below.
 */
import type { EnemyDef } from "../../game/types";

export const enemyDefinitions: Record<string, EnemyDef> = {
  rat: {
    id: "rat",
    name: "Cinder Rat",
    sprite: "enemy_rat",
    behavior: "swarm",
    hp: 2,
    damage: 1,
    speed: 78,
    radius: 6,
    embers: 2,
    fallbackColor: "#8a6a4a",
    aggroRange: 150,
    heartChance: 0.06,
  },
  ooze: {
    id: "ooze",
    name: "Ashen Ooze",
    sprite: "enemy_ooze",
    behavior: "chaser",
    hp: 4,
    damage: 1,
    speed: 46,
    radius: 7,
    embers: 3,
    fallbackColor: "#5fd08a",
    aggroRange: 170,
    heartChance: 0.12,
  },
  spider: {
    id: "spider",
    name: "Gloom Spider",
    sprite: "enemy_spider",
    behavior: "patroller",
    hp: 3,
    damage: 1,
    speed: 70,
    radius: 7,
    embers: 4,
    fallbackColor: "#cfc6b8",
    aggroRange: 140,
    heartChance: 0.08,
  },
  bat: {
    id: "bat",
    name: "Dusk Moth",
    sprite: "enemy_bat",
    behavior: "swarm",
    hp: 2,
    damage: 1,
    speed: 96,
    radius: 6,
    embers: 3,
    fallbackColor: "#c98a4a",
    aggroRange: 200,
    heartChance: 0.05,
  },
  wraith: {
    id: "wraith",
    name: "Hollow Wraith",
    sprite: "enemy_wraith",
    behavior: "shooter",
    hp: 4,
    damage: 1,
    speed: 40,
    radius: 7,
    embers: 6,
    fallbackColor: "#e8edf2",
    fireInterval: 2.0,
    projectileSpeed: 120,
    aggroRange: 240,
    heartChance: 0.14,
  },
  caster: {
    id: "caster",
    name: "Ember Cultist",
    sprite: "enemy_caster",
    behavior: "shooter",
    hp: 5,
    damage: 1,
    speed: 34,
    radius: 7,
    embers: 7,
    fallbackColor: "#9b6cc9",
    fireInterval: 1.7,
    projectileSpeed: 135,
    aggroRange: 260,
    heartChance: 0.16,
  },
  guard: {
    id: "guard",
    name: "Rusted Sentinel",
    sprite: "enemy_guard",
    behavior: "tank",
    hp: 9,
    damage: 2,
    speed: 40,
    radius: 8,
    embers: 9,
    fallbackColor: "#9aa3ad",
    aggroRange: 190,
    heartChance: 0.2,
  },

  // ---- Round 2: the Rootward Road (cursed creatures spilling from the Keep) ----
  husk: {
    id: "husk",
    name: "Rootbound Husk",
    sprite: "enemy_ooze",
    behavior: "splitter",
    hp: 5,
    damage: 1,
    speed: 52,
    radius: 8,
    embers: 5,
    fallbackColor: "#7a8a4a",
    aggroRange: 200,
    heartChance: 0.12,
    splitsInto: { ref: "huskling", count: 2 },
  },
  huskling: {
    id: "huskling",
    name: "Huskling",
    sprite: "enemy_ooze",
    behavior: "swarm",
    hp: 1,
    damage: 1,
    speed: 92,
    radius: 5,
    embers: 1,
    fallbackColor: "#9ab06a",
    aggroRange: 240,
    scale: 0.7,
  },
  thornCaster: {
    id: "thornCaster",
    name: "Thorn Effigy",
    sprite: "enemy_caster",
    behavior: "turret",
    hp: 6,
    damage: 1,
    speed: 0,
    radius: 7,
    embers: 7,
    fallbackColor: "#9b6cc9",
    fireInterval: 2.1,
    projectileSpeed: 130,
    aggroRange: 280,
    heartChance: 0.18,
  },
  roadKnight: {
    id: "roadKnight",
    name: "Wayward Knight",
    sprite: "enemy_guard",
    behavior: "charger",
    hp: 8,
    damage: 2,
    speed: 56,
    radius: 8,
    embers: 9,
    fallbackColor: "#8a7a6a",
    aggroRange: 240,
    heartChance: 0.2,
  },
  barrowChampion: {
    id: "barrowChampion",
    name: "The Barrow Champion",
    sprite: "enemy_guard",
    behavior: "charger",
    hp: 22,
    damage: 2,
    speed: 64,
    radius: 10,
    embers: 30,
    fallbackColor: "#caa14a",
    aggroRange: 320,
    scale: 1.6,
    elite: true,
    heartChance: 1,
  },

  // ---- Phase 3: The Saltblack Reach (a drowned war-coast) ----
  drownedKnight: {
    id: "drownedKnight",
    name: "Drowned Knight",
    sprite: "enemy_guard",
    behavior: "tank",
    hp: 11,
    damage: 2,
    speed: 38,
    radius: 9,
    embers: 11,
    fallbackColor: "#4a6a7a",
    aggroRange: 200,
    heartChance: 0.2,
  },
  tideArcher: {
    id: "tideArcher",
    name: "Brine Archer",
    sprite: "enemy_wraith",
    behavior: "shooter",
    hp: 4,
    damage: 1,
    speed: 46,
    radius: 7,
    embers: 7,
    fallbackColor: "#7fd0c8",
    fireInterval: 1.9,
    projectileSpeed: 140,
    aggroRange: 260,
    heartChance: 0.14,
  },
  gearTurret: {
    id: "gearTurret",
    name: "Tollworks Turret",
    sprite: "enemy_caster",
    behavior: "turret",
    hp: 7,
    damage: 1,
    speed: 0,
    radius: 7,
    embers: 8,
    fallbackColor: "#9aa3ad",
    fireInterval: 2.0,
    projectileSpeed: 135,
    aggroRange: 300,
    heartChance: 0.16,
  },
  mireCrawler: {
    id: "mireCrawler",
    name: "Mire Crawler",
    sprite: "enemy_ooze",
    behavior: "splitter",
    hp: 5,
    damage: 1,
    speed: 56,
    radius: 8,
    embers: 5,
    fallbackColor: "#5f8a6a",
    aggroRange: 210,
    heartChance: 0.12,
    splitsInto: { ref: "mireSpawn", count: 2 },
  },
  mireSpawn: {
    id: "mireSpawn",
    name: "Mire Spawn",
    sprite: "enemy_ooze",
    behavior: "swarm",
    hp: 1,
    damage: 1,
    speed: 95,
    radius: 5,
    embers: 1,
    fallbackColor: "#8aa07a",
    aggroRange: 240,
    scale: 0.7,
  },

  // ---- Phase 4: The Glass Country (a bright, refracted crystal land) ----
  glassMite: {
    id: "glassMite",
    name: "Glass Mite",
    sprite: "enemy_bat",
    behavior: "swarm",
    hp: 2,
    damage: 1,
    speed: 102,
    radius: 5,
    embers: 2,
    fallbackColor: "#a8e8ff",
    aggroRange: 210,
    heartChance: 0.05,
    scale: 0.85,
  },
  prismCaster: {
    id: "prismCaster",
    name: "Prism Caster",
    sprite: "enemy_caster",
    behavior: "turret",
    hp: 6,
    damage: 1,
    speed: 0,
    radius: 7,
    embers: 8,
    fallbackColor: "#c8a8ff",
    fireInterval: 2.2,
    projectileSpeed: 118,
    aggroRange: 300,
    heartChance: 0.16,
  },
  echoHound: {
    id: "echoHound",
    name: "Echo Hound",
    sprite: "sk_wolf",
    behavior: "charger",
    hp: 6,
    damage: 2,
    speed: 60,
    radius: 7,
    embers: 7,
    fallbackColor: "#9ab0c8",
    aggroRange: 240,
    heartChance: 0.15,
  },
  shardSentinel: {
    id: "shardSentinel",
    name: "Shard Sentinel",
    sprite: "sk_yeti",
    behavior: "tank",
    hp: 12,
    damage: 2,
    speed: 36,
    radius: 9,
    embers: 12,
    fallbackColor: "#bcd8e8",
    aggroRange: 200,
    heartChance: 0.2,
  },
};
