/**
 * characterDefinitions.ts — the 10 playable "Vessels".
 *
 * The Ember (the player) wears the form of a fallen champion. Each Vessel is a
 * Tiny Dungeon figure (pc_* sprite) paired with a DISTINCT procedural weapon
 * that animates on attack, an attack profile, and one signature perk — so the
 * choice changes both the look and the feel of the run. Picked on the
 * character-select screen and freely swapped at any Emberlight (checkpoint).
 *
 * All combat numbers are × multipliers on Balance.player baselines unless noted
 * (`damage` is absolute pips). Ranged Vessels (style "cast") deal damage only
 * through their projectiles — no melee — which is their built-in weakness.
 *
 * Pure data: the engine never imports this directly except through Game's roster.
 */
import type { CharacterDef } from "../../game/types";

export const characters: CharacterDef[] = [
  {
    id: "warden",
    name: "The Warden",
    role: "Balanced · Sword",
    sprite: "pc_warden",
    weapon: "sword",
    style: "swing",
    color: "#ffd98a",
    blurb: "The last knight of Emberfall. No weakness, no edge — just resolve. The safe first step.",
    perkName: "Warden's Heart",
    perkDesc: "+1 max heart. A clean, even blade for any situation.",
    damage: 1,
    reachMult: 1.0,
    arcMult: 1.0,
    cooldownMult: 1.0,
    speedMult: 1.0,
    enemyKnockbackMult: 1.0,
    heartsBonus: 1,
  },
  {
    id: "sentinel",
    name: "The Sentinel",
    role: "Tank · Warhammer",
    sprite: "pc_sentinel",
    weapon: "hammer",
    style: "swing",
    color: "#cfd6e0",
    blurb: "Plate from the Keep's first siege. The curse could not move it; little else can either.",
    perkName: "Bulwark",
    perkDesc: "+2 max hearts, shrugs off knockback, longer mercy after a hit. Slow, but hard to fell.",
    damage: 2,
    reachMult: 1.0,
    arcMult: 1.05,
    cooldownMult: 1.5,
    durationMult: 1.1,
    speedMult: 0.86,
    enemyKnockbackMult: 1.9,
    heartsBonus: 2,
    iframeBonus: 0.3,
    knockbackResist: 0.5,
  },
  {
    id: "reaver",
    name: "The Reaver",
    role: "Bruiser · Axe",
    sprite: "pc_reaver",
    weapon: "axe",
    style: "swing",
    color: "#f0a05a",
    blurb: "A road-warden gone feral. Swings first; remembers nothing. Carves tanks and crowds alike.",
    perkName: "Sunder",
    perkDesc: "Heavy, wide cleaves (double damage) that hurl foes back hard.",
    damage: 2,
    reachMult: 1.1,
    arcMult: 1.25,
    cooldownMult: 1.32,
    speedMult: 0.96,
    enemyKnockbackMult: 2.2,
  },
  {
    id: "lancer",
    name: "The Lancer",
    role: "Reach · Spear",
    sprite: "pc_lancer",
    weapon: "spear",
    style: "thrust",
    color: "#e6dca0",
    blurb: "Drilled to hold a line that drowned anyway. Still holds it — master of doorways and halls.",
    perkName: "Phalanx Reach",
    perkDesc: "A long thrust that spears every foe in its line. Strike before they reach you.",
    damage: 1,
    reachMult: 1.9,
    arcMult: 0.35,
    cooldownMult: 1.05,
    speedMult: 1.0,
    enemyKnockbackMult: 1.1,
  },
  {
    id: "duelist",
    name: "The Duelist",
    role: "Glass Cannon · Daggers",
    sprite: "pc_duelist",
    weapon: "dagger",
    style: "thrust",
    color: "#bfe8ff",
    blurb: "Quick hands from a quicker city. Gets in, gets out — mostly. Reward for nerve and footwork.",
    perkName: "Fleetfoot",
    perkDesc: "Blinding flurries and a quicker roll, but short reach — you must close the distance.",
    damage: 1,
    reachMult: 0.78,
    arcMult: 0.7,
    cooldownMult: 0.5,
    durationMult: 0.85,
    speedMult: 1.08,
    enemyKnockbackMult: 0.6,
    dashCooldownMult: 0.7,
  },
  {
    id: "embermage",
    name: "The Embermage",
    role: "Ranged · Staff",
    sprite: "pc_embermage",
    weapon: "staff",
    style: "cast",
    color: "#ff8a3c",
    blurb: "Read one forbidden page too many; now the fire answers. Melts foes before they arrive.",
    perkName: "Pyromancy",
    perkDesc: "Hurls heavy ember-bolts from range. No melee — keep your distance and your nerve.",
    damage: 2,
    reachMult: 1.0,
    arcMult: 1.0,
    cooldownMult: 1.2,
    speedMult: 0.95,
    ranged: { projectileSpeed: 230, shots: 1 },
  },
  {
    id: "wayfarer",
    name: "The Wayfarer",
    role: "Ranged · Bow",
    sprite: "pc_wayfarer",
    weapon: "bow",
    style: "cast",
    color: "#9fe8c0",
    blurb: "Walked every cursed mile and lived. Knows the value of distance. Kite, loose, repeat.",
    perkName: "Piercing Shot",
    perkDesc: "Fast arrows that punch through one foe into the next. No melee, but always moving.",
    damage: 1,
    reachMult: 1.0,
    arcMult: 1.0,
    cooldownMult: 0.66,
    speedMult: 1.04,
    ranged: { projectileSpeed: 320, pierce: 1 },
  },
  {
    id: "revenant",
    name: "The Revenant",
    role: "Sustain · Scythe",
    sprite: "pc_revenant",
    weapon: "scythe",
    style: "swing",
    color: "#b48cff",
    blurb: "Died at the Echo Well; came back owing the curse a debt — and collecting it, foe by foe.",
    perkName: "Harvest",
    perkDesc: "Each reaped foe may mend a wound. Outlasts long, grinding rooms.",
    damage: 1,
    reachMult: 1.18,
    arcMult: 1.15,
    cooldownMult: 1.0,
    speedMult: 0.98,
    enemyKnockbackMult: 1.0,
    lifestealChance: 0.35,
  },
  {
    id: "adept",
    name: "The Adept",
    role: "Crowd Control · Quarterstaff",
    sprite: "pc_adept",
    weapon: "quarterstaff",
    style: "spin",
    color: "#7fd6ff",
    blurb: "Last of an order that swept the Glass Country clean. The sweep remains. Born for swarms.",
    perkName: "Whirl",
    perkDesc: "A spinning staff that strikes in every direction at once. Ambushes mean nothing.",
    damage: 1,
    reachMult: 1.12,
    arcMult: 2.0,
    cooldownMult: 0.95,
    durationMult: 1.15,
    speedMult: 1.02,
    enemyKnockbackMult: 1.3,
  },
  {
    id: "saltblade",
    name: "The Saltblade",
    role: "Pressure · Cutlass",
    sprite: "pc_saltblade",
    weapon: "cutlass",
    style: "swing",
    color: "#5ad6e0",
    blurb: "Cutlass off a ship the Reach swallowed whole. Fights like the tide: again, and again, and again.",
    perkName: "Riptide",
    perkDesc: "Quick, relentless cuts — pressure that never lets a foe set their feet.",
    damage: 1,
    reachMult: 1.02,
    arcMult: 0.95,
    cooldownMult: 0.72,
    durationMult: 0.9,
    speedMult: 1.04,
    enemyKnockbackMult: 0.9,
  },
];

export const defaultCharacterId = "warden";

const byId = new Map(characters.map((c) => [c.id, c]));

/** Resolve an id to a CharacterDef, falling back to the default Vessel. */
export function characterById(id: string | null | undefined): CharacterDef {
  return (id && byId.get(id)) || characters[0];
}
